
export enum InvestmentTypeEnum {
  STOCK = "STOCK",
  ETF = "ETF",
  MUTUAL_FUND = "MUTUAL_FUND",
  BOND = "BOND",
  FIXED_DEPOSIT = "FIXED_DEPOSIT",
  GOLD = "GOLD",
  SILVER = "SILVER",
  REAL_ESTATE = "REAL_ESTATE",
  CRYPTO = "CRYPTO",
  PENSION = "PENSION",
  PROVIDENT_FUND = "PROVIDENT_FUND",
  BUSINESS = "BUSINESS",
  STARTUP = "STARTUP",
  COMMODITY = "COMMODITY",
  OTHER = "OTHER",
}