import * as dotenv from "dotenv";
dotenv.config();
const mongoose = require("mongoose");
import { categoryModel } from "../models";

const url = process.env.MONGO_URL!;

export const seedDefaultRole = async () => {
  try {
    mongoose.connect(url, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
  
      const categories = [
  // ==========================
  // Expense Categories
  // ==========================

  {
    name: "Food",
    slug: "food",
    type: "expense",
    user: null,
    icon: "",
    color: "#FF6B6B",
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    name: "Transportation",
    slug: "transportation",
    type: "expense",
    user: null,
    icon: "",
    color: "#4ECDC4",
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    name: "Shopping",
    slug: "shopping",
    type: "expense",
    user: null,
    icon: "",
    color: "#45B7D1",
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    name: "Bills",
    slug: "bills",
    type: "expense",
    user: null,
    icon: "",
    color: "#F39C12",
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    name: "Rent",
    slug: "rent",
    type: "expense",
    user: null,
    icon: "",
    color: "#9B59B6",
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    name: "Healthcare",
    slug: "healthcare",
    type: "expense",
    user: null,
    icon: "",
    color: "#E74C3C",
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    name: "Education",
    slug: "education",
    type: "expense",
    user: null,
    icon: "",
    color: "#2ECC71",
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    name: "Entertainment",
    slug: "entertainment",
    type: "expense",
    user: null,
    icon: "",
    color: "#8E44AD",
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    name: "Travel",
    slug: "travel",
    type: "expense",
    user: null,
    icon: "",
    color: "#3498DB",
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    name: "Utilities",
    slug: "utilities",
    type: "expense",
    user: null,
    icon: "",
    color: "#16A085",
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    name: "Insurance",
    slug: "insurance",
    type: "expense",
    user: null,
    icon: "",
    color: "#D35400",
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    name: "Gifts",
    slug: "gifts",
    type: "expense",
    user: null,
    icon: "",
    color: "#E84393",
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    name: "Personal Care",
    slug: "personal-care",
    type: "expense",
    user: null,
    icon: "",
    color: "#00CEC9",
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    name: "Other Expense",
    slug: "other-expense",
    type: "expense",
    user: null,
    icon: "",
    color: "#636E72",
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },

  // ==========================
  // Income Categories
  // ==========================

  {
    name: "Salary",
    slug: "salary",
    type: "income",
    user: null,
    icon: "",
    color: "#2ECC71",
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    name: "Bonus",
    slug: "bonus",
    type: "income",
    user: null,
    icon: "",
    color: "#27AE60",
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
   {
    name: "Holiday Pay",
    slug: "holiday-pay",
    type: "income",
    user: null,
    icon: "",
    color: "#89AE62",
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    name: "Freelance",
    slug: "freelance",
    type: "income",
    user: null,
    icon: "",
    color: "#2980B9",
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    name: "Business",
    slug: "business",
    type: "income",
    user: null,
    icon: "",
    color: "#8E44AD",
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    name: "Investment",
    slug: "investment",
    type: "income",
    user: null,
    icon: "",
    color: "#16A085",
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    name: "Interest",
    slug: "interest",
    type: "income",
    user: null,
    icon: "",
    color: "#F1C40F",
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    name: "Rental Income",
    slug: "rental-income",
    type: "income",
    user: null,
    icon: "",
    color: "#D35400",
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    name: "Gift",
    slug: "gift",
    type: "income",
    user: null,
    icon: "",
    color: "#E84393",
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    name: "Refund",
    slug: "refund",
    type: "income",
    user: null,
    icon: "",
    color: "#00B894",
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    name: "Other Income",
    slug: "other-income",
    type: "income",
    user: null,
    icon: "",
    color: "#636E72",
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
];
      

    await categoryModel.insertMany(categories);
    console.log("default categories seeded successfully!");

  } catch (error) {
    console.error("Error seeding default categories:", error);
  } finally {
    mongoose.disconnect();
  }
};

seedDefaultRole();
